name: Build Mnemosyne Claude Desktop Extension

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.19.0'
          cache: 'npm'
      - run: npm install
      - run: npx @anthropic-ai/mcpb pack
      - uses: softprops/action-gh-release@v2
        with:
          files: mnemosyne.mcpb
          generate_release_notes: true
          tag_name: ${{ github.ref_name }}
