name: Build Mnemosyne Claude Desktop Extension

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.19.0'
          cache: 'npm'
      - run: npm install
      - run: npx @anthropic-ai/mcpb pack
      - uses: actions/upload-artifact@v4
        with:
          name: mnemosyne
          path: mnemosyne.mcpb
